### ISSUE TITLE
C128 80 col mode

### ISSUE THREAD

**Issue by toddbailey98014** [KimJorgensen/KungFuFlash#196] opened 2024-07-26 03:20 UTC
Hi,

I'm trying to run apps in 80 col mode on a c128.  The KFF says the prg loads ok but I haven't found a way to switch to 80 col mode and run the program.
I'm new to the C128 machine and KFF in general.  Is this a feature request or a operator error issue?

I'm also having issues getting c64 text games (infocom etc) to run in c64 mode

any ideas

**Comment by KimJorgensen** [comment] 2024-07-26 11:54
Loading PRG files in C128 mode is currently not supported and is a duplicate of #88

Can you describe what issues you have with the C64 text games? It's hard to guess without more context

**Comment by toddbailey98014** [comment] 2024-07-27 04:17
The files I'm trying to run are .d71.  I'm not sure if it's a c64 or c128 binary nor what video mode if a c128 file.
Hopefully adding c128 compatibility is planned
Meanwhile I'll play with the 128 and see what other info I can gather
________________________________

**Closed** 2024-12-29 14:43 UTC
