### ISSUE TITLE
Feature request: custom kernal

### ISSUE THREAD

**Issue by sorgelig** [KimJorgensen/KungFuFlash#145] opened 2022-10-30 23:30 UTC
Is it possible to add a custom kernal loading like it's done in EasyFlash 3?
For example, if i want to use use Pi1541 for D64 it would be good to load JiffyDOS from KFF. So once kernal selected, C64 will boot straight into it.

**Comment by KimJorgensen** [comment] 2022-11-08 19:48
It is not possible, but there is a fork of Kung Fu Flash with soft-kernal support (https://github.com/medzes/KungFuFlash)
The best you can do now is to load a fastload or freezer cartridge.

I'll close this as a duplicate of #14

**Closed by KimJorgensen** 2022-11-08 19:48 UTC
