### ISSUE TITLE
Easy Flash version of Epyx Games Collection crashing.. 

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#61] opened 2020-12-01 15:46 UTC
https://csdb.dk/release/?id=107705

I tried this great release with v1.16 and everything works but the Summer Games I, it crashes when leaving the "lightning the flame" scene. In WinVICE-3.2-x86 it works.
Does this work in a real Easy Flash? I don't have one but if so maybe a small bug still there?

**Comment by KimJorgensen** [comment] 2020-12-01 17:43
I cannot reproduce this issue. Are you using a stock C64 without a disk drive connected?

**Comment by mwedmark** [comment] 2020-12-01 17:48
Yes breadbox working 100% played original SG1 many times. For now a
TapecartSd is connected to tapeport. I will try without. All other games on
that image work.. strange. But ok then it is just my C64 bb then.. thought
is was a bug.

Den tis 1 dec. 2020 18:43Kim Jørgensen <notifications@github.com> skrev:

**Comment by mwedmark** [comment] 2020-12-07 22:43
Still hanging om that release and only for that scene. Must be something specific to this computer/old Breadbox-model and this release of the game or particular timing thingy with KFF.. Well as long as it works for everybody else maybe we should close this issue.

**Comment by KimJorgensen** [comment] 2020-12-09 18:35
Did you try to test it on a different C64?
I tried it 5 different machines with no crash but it could be that your particular model has different timing characteristics.

**Comment by mwedmark** [comment] 2020-12-09 18:52
No sorry I only have my old C64 Breadbox from 1983, here's the details of it if that is of any help.. I can build local test firmwares myself if you want me to test anything but I wouldn't know what to change..

Mugshot of the prosecuted:
![20190106_162130](https://user-images.githubusercontent.com/2123085/101673750-dda3d700-3a57-11eb-963e-a7c89172c70a.jpg)

**Comment by KimJorgensen** [comment] 2020-12-09 19:15
Svenska?
Interesting looking PLA. I don't think I have tested a C64 with that version but now I need to get one.

**Comment by modeler** [comment] 2020-12-16 09:29
That's a 251064-01 PLA, I have a few. No compatibility issues that I know of, I can try this cart and PLA combination if that helps.

**Comment by mwedmark** [comment] 2020-12-16 09:37
Yes probably worth doing. As far as I know, everything else is working 100%
on this computer. But of course, could be just this individual as it's 35+
years old.
Do you know of any big, thorough function test that can be executed to
check everything regarding PLA, Memory, ports?

Den ons 16 dec. 2020 kl 10:29 skrev Daniel Tootill <notifications@github.com

**Comment by modeler** [comment] 2020-12-16 10:44
Tested in my 250407 Rev. B board using the CSG 251064-01 PLA, no issues here.

If you wanted to do a rigorous test of your C64 you'd need the 586220 diagnostics (see http://blog.worldofjani.com/?p=164), but most of the tests would fail without the harness. I built my own using Sven Petersen's reworking:

https://github.com/svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness

**Comment by KimJorgensen** [comment] 2024-12-29 15:22
I assume that the original issue was due to a timing problem that can be fixed by adjusting the phi2 offset. Otherwise feel free to create a new issue

**Closed by KimJorgensen** 2024-12-29 15:22 UTC
