### ISSUE TITLE
Saving game process 

### ISSUE THREAD

**Issue by mauiphill** [KimJorgensen/KungFuFlash#211] opened 2024-12-29 06:42 UTC
Can anyone tell me how to save game progress on the Kung Fu Flash 2 please.

**Comment by KimJorgensen** [comment] 2024-12-29 14:35
Kung Fu Flash does not have a general save state feature. However, it can emulate freezers like Action Replay or Super Snapshot. Writing to flash is also supported for EasyFlash CRT releases (#8).

I'll close this issue as a duplicate of #46 and #178.

**Closed by KimJorgensen** 2024-12-29 14:35 UTC
