### ISSUE TITLE
Does not work with jiffydos running on c64

### ISSUE THREAD

**Issue by ogg1e** [KimJorgensen/KungFuFlash#40] opened 2020-10-15 20:35 UTC
I have to disable jiffydos on the c64 for this to work .

**Comment by modeler** [comment] 2020-11-03 07:59
Mine works fine with my C64 that has JaffyDOS (Jani's fork of JiffyDOS), if that helps?

**Comment by KimJorgensen** [comment] 2020-11-30 17:24
This is a duplicate of #33 so I'll close this

**Closed by KimJorgensen** 2020-11-30 17:24 UTC
Labels: duplicate
