### ISSUE TITLE
GD32f405

### ISSUE THREAD

**Issue by retroman75** [KimJorgensen/KungFuFlash#134] opened 2022-09-04 09:56 UTC
Any chances to have support for those cheap GD32f405 chips ? 
Thank you

**Comment by KimJorgensen** [comment] 2022-09-04 10:05
No, but @Sgw32 did this fork https://github.com/Sgw32/KungFuFlashGD32

I'll close this issue as a duplicate of #125

**Closed by KimJorgensen** 2022-09-04 10:05 UTC
