### ISSUE TITLE
NTSC "TODO" documentation

### ISSUE THREAD

**Issue by rihardgDev** [KimJorgensen/KungFuFlash#41] opened 2020-10-23 12:35 UTC
Hello, first of all I would like to express admiration for this wonderful project. I've been using Kung Fu Flash for couple of months and I must say I use ti much more than my Pi1451. I've wanted to help spread the world about this wonderful and versatile cart so I've created a blog with hopefully easy to understand instructions on how to build it: https://8bithardware.wixsite.com/website/post/kung-fu-flash (you can link it, if you think it's useful). I've been promoting it via Facebook groups and the general opinion is very good. With one exception, the NTSC part of the community feels left out. I think that adding NTSC would benefit the project greatly. With bigger audience, you automatically attract more developers and new features bring in even more new users and so on...

I know that the main reason for lacking the NTSC is that you don't have a NTSC C64, so i think it might be worth to try to find a developer who has one. I'm pretty sure that there must be some talented people from NTSC world that would be interested in implementing this feature. To ease this process, I would propose that a "TODO" documentation is made, describing what in general needs to be done and how it's implemented on PAL version. I think we all agree it's easier to start if there is at least a basic documentation/idea whats to be done.

One gentlemen on C64 Facebook group even said it can't be done because it's already running on the edge of the CPU capabilities etc...
With a short document describing the basic requirements and where in the current code is PAL implementation this kind of dilemmas would be resolved and I'm pretty sure someone would start implementing it.

I really think this is successor of the Easy Flash 3 and a drastic enhancement of its capabilities and it deserves to be widespread! Thank you for your gift to the community!

**Comment by KimJorgensen** [comment] 2020-12-17 19:06
I'll close this as a duplicate of #6

**Closed by KimJorgensen** 2020-12-17 19:06 UTC
Labels: documentation
